// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlaySoftBeta.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230324174719_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlaySoftBeta.Models.Playlist", b =>
                {
                    b.Property<int>("playlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playlistID"));

                    b.Property<string>("playListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playlistDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("privacity")
                        .HasColumnType("bit");

                    b.Property<int>("userUKID")
                        .HasColumnType("int");

                    b.HasKey("playlistID");

                    b.HasIndex("userUKID");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.PlaylistLines", b =>
                {
                    b.Property<int>("playlistID")
                        .HasColumnType("int");

                    b.Property<int>("songID")
                        .HasColumnType("int");

                    b.HasKey("playlistID", "songID");

                    b.HasIndex("songID");

                    b.ToTable("PlaylistLines");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.Song", b =>
                {
                    b.Property<int>("songID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("songID"));

                    b.Property<DateTime>("publicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("songName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("songID");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            songID = 1,
                            publicationDate = new DateTime(2015, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            songName = "pumbaPumba"
                        },
                        new
                        {
                            songID = 2,
                            publicationDate = new DateTime(2021, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            songName = "Temardo bien de guapo"
                        },
                        new
                        {
                            songID = 3,
                            publicationDate = new DateTime(1015, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            songName = "AngryBirdsSongTheme"
                        });
                });

            modelBuilder.Entity("PlaySoftBeta.Models.User", b =>
                {
                    b.Property<int>("UKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UKID"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UKID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.Playlist", b =>
                {
                    b.HasOne("PlaySoftBeta.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("userUKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.PlaylistLines", b =>
                {
                    b.HasOne("PlaySoftBeta.Models.Playlist", "Playlist")
                        .WithMany("PlaylistLines")
                        .HasForeignKey("playlistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlaySoftBeta.Models.Song", "Song")
                        .WithMany("PlaylistLines")
                        .HasForeignKey("songID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistLines");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.Song", b =>
                {
                    b.Navigation("PlaylistLines");
                });

            modelBuilder.Entity("PlaySoftBeta.Models.User", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
