version: '3.9'
services:
  api:
    build: .
      context: . 
    ports:
      - "5945:80"
    environment:
      ASPNETCORE_ENVIROMENT: Development
      ConnectionStrings_DefaultConnection: "Server=db;Database=MyDatabase;User Id=sa;Password=MyPassword123;"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: MyPassword123
      ACCEPT_EULA: Y
